[package]
name = "pairings"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
serde = { version = "1.0", features = ["derive"] }
pairings-derive = { path = "./derive/" }
